server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false
    username: root
    password: RoadToHell_99
  jpa:
    hibernate:
      ddl-auto: create
jpa:
  show-sql: true
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
indexing-settings:
  sites:
#    - url: https://www.lenta.ru
#      name: Лента.ру
#    - url: https://www.skillbox.ru
#      name: Skillbox
#    - url: https://www.playback.ru
#      name: PlayBack.Ru
    - url: https://ipfran.ru
      name: ipfran.ru
